spring:
  data:
    redis:
      password: ${REDIS_PASSWORD}
      sentinel:
        master: mymaster
        password: ${REDIS_PASSWORD}
        nodes:
          - idporten-redis-sentinel-node-0.idporten-redis-sentinel-headless:26379
          - idporten-redis-sentinel-node-1.idporten-redis-sentinel-headless:26379
          - idporten-redis-sentinel-node-2.idporten-redis-sentinel-headless:26379