---
server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: false
    database-platform: org.hibernate.dialect.MariaDB103Dialect
  flyway:
    table: flyway_schema_history
  security:
    user:
      name: user
      password: password
  application:
    name: idporten-user-service
    environment: 

# Spring Boot Actuator
management:
  server:
    port: 8090
  endpoints:
    web:
      base-path: /
      exposure:
        include: info,version,prometheus,health
  endpoint:
    health:
      group:
        readiness:
          include: db
        liveness:
          include: livenessState
        diskspace:
          enabled: false
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

# Swagger with springdoc
springdoc:
  api-docs:
    groups:
      enabled: true
  group-configs:
    - group: Admin API
      paths-to-match: /admin/v1/**
    - group: Login API
      paths-to-match: /login/v1/**
  swagger-ui:
    display-request-duration: true
    disable-swagger-default-url: true
    use-root-path: true

# App-specific config
idporten-user-service:
  audit:
    application-name: ${spring.application.name}
    audit-log-dir:
  features:
    allow-real-pid: true
    allow-synthetic-pid: false
  whitelist-config:
    security:
      get-allowed:
        - /
        - /health/**
        - /version
        - /info
        - /prometheus
        - /swagger-ui.html
        - /swagger-ui/**
        - /v3/api-docs/**
        - /error

---
spring:
  config:
    activate:
      on-cloud-platform: 'kubernetes'
    import:
      - 'optional:file:/etc/config/'
