---
spring:
  datasource:
    url: jdbc:mariadb://user-service-mariadb:3306/idporten_user
    password: ${DATASOURCE_PASSWORD}
    username: user_service
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-timeout: 6000 #maximum number of milliseconds that a client will wait for a connection
      minimum-idle: 5 #minimum number of idle connections maintained by HikariCP in a connection pool
      maximum-pool-size: 5 #maximum pool size
      idle-timeout: 10000 #maximum idle time for connection
      max-lifetime: 1000 # maximum lifetime in milliseconds of a connection in the pool after it is closed.
  security:
    api-key: ${API_KEY}
    oauth2:
      resource:
        jwt:
          jwk-set-uri: https://maskinporten.no/.well-known/jwks.json
  application:
    environment: prod
  data:
    redis:
      password: ${REDIS_PASSWORD}
      sentinel:
        master: mymaster
        nodes:
          - idporten-redis-sentinel-node-0.idporten-redis-sentinel-headless:26379
          - idporten-redis-sentinel-node-1.idporten-redis-sentinel-headless:26379
          - idporten-redis-sentinel-node-2.idporten-redis-sentinel-headless:26379
        password: ${REDIS_PASSWORD}
