spring:
  data:
    redis:
      password: ${REDIS_PASSWORD}
      sentinel:
        master: mymaster
        password: ${REDIS_PASSWORD}
        nodes:
          - ansattporten-redis-sentinel-node-0.ansattporten-redis-sentinel-headless:26379
          - ansattporten-redis-sentinel-node-1.ansattporten-redis-sentinel-headless:26379
          - ansattporten-redis-sentinel-node-2.ansattporten-redis-sentinel-headless:26379
