---
server:
  port: 8080

spring:
  cache:
    type: redis
  data:
    redis:
      connect-timeout: 3s
      timeout: 3s
  thread-executor: virtual
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: false
    database-platform: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
  flyway:
    table: flyway_schema_history
  application:
    name: idporten-user-service
    environment: default

# Spring Boot Actuator
management:
  server:
    port: 8090
  endpoints:
    web:
      base-path: /
      exposure:
        include: info,version,prometheus,health
  endpoint:
    health:
      group:
        readiness:
          include: db
        liveness:
          include: livenessState
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      environment: ${spring.application.environment}

# Swagger with springdoc
springdoc:
  api-docs:
    groups:
      enabled: true
  group-configs:
    - group: Admin API
      paths-to-match: /admin/v1/**
    - group: Login API
      paths-to-match: /login/v1/**
  swagger-ui:
    display-request-duration: true
    disable-swagger-default-url: true
    use-root-path: true

# App-specific config
idporten-user-service:
  features:
    allow-real-pid: true
    allow-synthetic-pid: false
  whitelist-config:
    security:
      get-allowed:
        - /
        - /health/**
        - /version
        - /info
        - /prometheus
        - /swagger-ui.html
        - /swagger-ui/**
        - /v3/api-docs/**
        - /error

digdir:
  caching:
    enabled: true
    time_to_live_in_days: 365
  audit:
    application-name: ${spring.application.name}
    application-environment: ${spring.application.environment}
    audit-log-dir:
    filters:
      bearer-token: false
  event:
    logging:
      environment-name: ${spring.application.environment}

---
spring:
  config:
    activate:
      on-cloud-platform: 'kubernetes'
    import:
      - 'optional:file:/etc/config/'
