---
server:
  port: 7080
management:
  server:
    port:
spring:
  datasource:
    url: "jdbc:h2:mem:idporten_user;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE"
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  security:
    token: mytoken
    oauth2:
      resource:
        jwt:
          jwk-set-uri: https://maskinporten.dev/.well-known/jwks.json
  application:
    environment: local-h2

# App-specific config
idporten-user-service:
  features:
    allow-real-pid: false
    allow-synthetic-pid: true
