---
management:
  endpoint:
    health:
      show-details: always
      show-components: always
spring:
  datasource:
    url: jdbc:mariadb://ansattporten-user-service-mariadb:3306/ansattporten_user
    password: ${DATASOURCE_PASSWORD}
    username: user_service
  security:
    api-key: ${API_KEY}
  application:
    environment: systest

# App-specific config
idporten-user-service:
  features:
    allow-real-pid: true
    allow-synthetic-pid: true
