---
server:
  port: 7080
management:
  server:
    port:
spring:
  datasource:
    url: "jdbc:mariadb://localhost:3306/idporten_user"
    username: user_service
    password: password
  security:
    api-key: mytoken
  application:
    environment: local-dev

# App-specific config
idporten-user-service:
  features:
    allow-real-pid: false
    allow-synthetic-pid: true
