---
server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: false
    database-platform: org.hibernate.dialect.MariaDB103Dialect
  flyway:
    table: flyway_schema_history


project:
  version: '@project.version@'

# Spring Boot Actuator
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info,version,prometheus
  endpoint:
    health:
      group:
        readiness:
          include: db
        liveness:
          include: livenessState
        diskspace:
          enabled: false
      probes:
        enabled: true
      show-details: never


  info:
    git:
      mode: full
  metrics:
    tags:
      application: "IDporten-user-service"

# Swagger with springdoc
springdoc:
  api-docs:
    groups:
      enabled: true
  group-configs:
    - group: CRUD API
      paths-to-match: /users/**
    - group: Identity Management API
      paths-to-match: /im/**
  swagger-ui:
    display-request-duration: true
    disable-swagger-default-url: true
    use-root-path: true

# App-specific config
idporten-user-service:
  features:
    allow-real-pid: true
    allow-synthetic-pid: false

---
spring:
  config:
    activate:
      on-cloud-platform: 'kubernetes'
    import:
      - 'optional:file:/etc/config/'
