---
spring:
  datasource:
    url: jdbc:mariadb://ansattporten-user-service-mariadb:3306/ansattporten_user
    password: ${DATASOURCE_PASSWORD}
    username: user_service
  security:
    api-key: ${API_KEY}
  application:
    environment: prod
