# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build/publish Docker image

on:
  push:
    branches: [ main ]

jobs:
  call-workflow-image-build-publish:
    uses: felleslosninger/eid-github-workflows/.github/workflows/eid-spring-boot-build-publish-image-generic.yml@work/ID-1627
    with:
      image-name: idporten-user-service
      allure-enabled: false
    secrets:
      eid-build-token: ${{ secrets.EID_BUILD_PAT }}
      maven-user: ${{ secrets.MAVEN_USER }}
      maven-password: ${{ secrets.MAVEN_PASSWORD }}
      registry-url: ${{ secrets.REGISTRY_URL }}
      registry-username: ${{ secrets.REGISTRY_USERNAME }}
      registry-password: ${{ secrets.REGISTRY_PASSWORD }}
      allure-user: ${{ secrets.ALLURE_USER }}
      allure-password: ${{ secrets.ALLURE_PASSWORD }}
