# This workflow will build a Spring Boot/Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build/publish Docker image

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'src/test/**'
      - 'docker/**'
      - 'docker-compose.yaml'
      - '*.md'
      - 'LICENSE'

jobs:
  build-publish-image:
    uses: felleslosninger/eid-github-workflows/.github/workflows/spring-boot-build-publish-image.yml@main
    with:
      image-name: idporten-user-service
      java-version: 21
    secrets:
      maven-user: ${{ secrets.MAVEN_USER }}
      maven-password: ${{ secrets.MAVEN_PASSWORD }}
      registry-url: ${{ secrets.REGISTRY_URL }}
      registry-username: ${{ secrets.REGISTRY_USERNAME }}
      registry-password: ${{ secrets.REGISTRY_PASSWORD }}
  update-image-version:
    uses: felleslosninger/eid-github-workflows/.github/workflows/update-image-version.yml@main
    needs: build-publish-image
    with:
      image-name: idporten-user-service
      image-version: ${{ needs.build-publish-image.outputs.image-version }}
      image-digest: ${{ needs.build-publish-image.outputs.image-digest }}
    secrets:
      eid-build-token: ${{ secrets.EID_BUILD_PAT }}
      registry-url: ${{ secrets.REGISTRY_URL }}
