# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Testing maven build by calling reusable workflow

on:
  pull_request:
    branches: [ main ]

jobs:
  call-workflow-maven-build:
    uses: felleslosninger/eid-github-workflows/.github/workflows/eid-maven-build.yml@main
    with:
      java-version: 17
    secrets:
      maven-user: ${{ secrets.MAVEN_USER }}
      maven-password: ${{ secrets.MAVEN_PASSWORD }}
  call-container-scan:
    uses: felleslosninger/eid-github-workflows/.github/workflows/eid-spring-boot-container-scan.yml@main
    with:
      image-name: idporten-user-service
      java-version: 17
    secrets:
      eid-build-token: ${{ secrets.EID_BUILD_PAT }}
      maven-user: ${{ secrets.MAVEN_USER }}
      maven-password: ${{ secrets.MAVEN_PASSWORD }}
