# This workflow will build a Spring Boot/Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build/publish Docker image

on:
  push:
    branches: [main]
    paths-ignore:
      - "src/test/**"
      - "docker/**"
      - "docker-compose.yaml"
      - "*.md"
      - "LICENSE"
      - "catalog-info.yaml"
      - ".github/pull_request_template.md"

jobs:
  build-publish-image:
    uses: felleslosninger/github-workflows/.github/workflows/ci-spring-boot-build-publish-image.yml@main
    with:
      image-name: idporten-user-service
      java-version: 21
    secrets: inherit

  call-update-image:
    uses: felleslosninger/github-workflows/.github/workflows/ci-call-update-image.yml@main
    needs: build-publish-image
    strategy:
      matrix:
        application-name: [ idporten-user-service, ansattporten-user-service ]
        include:
          - application-name: idporten-user-service
            product-name: idporten
          - application-name: ansattporten-user-service
            product-name: ansattporten
    with:
      application-name: ${{ matrix.application-name }}
      deployment-environment: systest
      image-digest: ${{ needs.build-publish-image.outputs.image-digest }}
      image-name: idporten-user-service
      image-version: ${{ needs.build-publish-image.outputs.image-version }}
      kubernetes-repo: idporten-cd
      product-name: ${{ matrix.product-name }}
    secrets: inherit
